<?php
/* 
 * This has the current default translation list for English (iso_code en).
 */

class trans_list_en {
    static public function getLanguageArray(){
        $lang_arr = array();
        $lang_arr[] = array('iso_code' => 'en');
        $lang_arr[] = array('term_name' => 'loading_message', 'value' => '<img alt="Loading" src="image/wait.gif"></br>Loading...Please Wait');
        $lang_arr[] = array('term_name' => 'users_teams', 'value' => 'Subscribed Teams');
        $lang_arr[] = array('term_name' => 'avail_teams', 'value' => 'Available Teams');
        $lang_arr[] = array('term_name' => 'avail_users', 'value' => 'Available Users');
        $lang_arr[] = array('term_name' => 'team_members', 'value' => 'Team Members');
        $lang_arr[] = array('term_name' => 'tasks_title_all', 'value' => 'All Tasks');
        $lang_arr[] = array('term_name' => 'depot_title', 'value' => 'All Items');
        $lang_arr[] = array('term_name' => 'hours_remain', 'value' => 'hours remain');
        $lang_arr[] = array('term_name' => 'hours_worked', 'value' => 'hours worked');
        $lang_arr[] = array('term_name' => 'drag_object_reorder', 'value' => 'Drag an object to reorder.');
        $lang_arr[] = array('term_name' => 'please_log_in', 'value' => 'Please Log In');
        $lang_arr[] = array('term_name' => 'please_wait', 'value' => 'Loading...Please Wait');
        $lang_arr[] = array('term_name' => 'loading', 'value' => 'Loading');
        $lang_arr[] = array('term_name' => 'status_link', 'value' => 'Status');
        $lang_arr[] = array('term_name' => 'comment_link', 'value' => 'Share');
        $lang_arr[] = array('term_name' => 'enter_text', 'value' => 'Your Text');
        $lang_arr[] = array('term_name' => 'tags_link', 'value' => 'Tags');
        $lang_arr[] = array('term_name' => 'file_link', 'value' => 'Files');
        $lang_arr[] = array('term_name' => 'team_link', 'value' => 'Team');
        $lang_arr[] = array('term_name' => 'schedule_link', 'value' => 'Plan');
        $lang_arr[] = array('term_name' => 'sub_link', 'value' => 'Subs');
        $lang_arr[] = array('term_name' => 'title_target_tasks', 'value' => 'Target Tasks');
        $lang_arr[] = array('term_name' => 'title_updated_items', 'value' => 'Updated Items');
        $lang_arr[] = array('term_name' => 'title_reports', 'value' => 'Reports');
        $lang_arr[] = array('term_name' => 'title_default_reports', 'value' => 'General Reports');
        $lang_arr[] = array('term_name' => 'title_space_reports', 'value' => 'Space Reports');
        $lang_arr[] = array('term_name' => 'title_admin_tools', 'value' => 'Admin Tools');
        $lang_arr[] = array('term_name' => 'title_space_admin', 'value' => 'Space Admin');
        $lang_arr[] = array('term_name' => 'title_search', 'value' => 'Search Results');
        $lang_arr[] = array('term_name' => 'no_information_available', 'value' => 'No information available.');
        $lang_arr[] = array('term_name' => 'time_format_just_now', 'value' => 'just now');
        $lang_arr[] = array('term_name' => 'time_format_one_minute_ago', 'value' => '1 minute ago');
        $lang_arr[] = array('term_name' => 'time_format_x_minutes_ago', 'value' => ' minutes ago');
        $lang_arr[] = array('term_name' => 'time_format_one_hour_ago', 'value' => '1 hour ago');
        $lang_arr[] = array('term_name' => 'time_format_x_hours_ago', 'value' => ' hours ago');
        $lang_arr[] = array('term_name' => 'time_format_one_day_ago', 'value' => 'Yesterday');
        $lang_arr[] = array('term_name' => 'time_format_x_days_ago', 'value' => ' days ago');
        $lang_arr[] = array('term_name' => 'time_format_x_weeks_ago', 'value' => ' weeks ago');
        $lang_arr[] = array('term_name' => 'month_names_short_0', 'value' => 'Jan');
        $lang_arr[] = array('term_name' => 'month_names_short_1', 'value' => 'Feb');
        $lang_arr[] = array('term_name' => 'month_names_short_2', 'value' => 'Mar');
        $lang_arr[] = array('term_name' => 'month_names_short_3', 'value' => 'Apr');
        $lang_arr[] = array('term_name' => 'month_names_short_4', 'value' => 'May');
        $lang_arr[] = array('term_name' => 'month_names_short_5', 'value' => 'Jun');
        $lang_arr[] = array('term_name' => 'month_names_short_6', 'value' => 'Jul');
        $lang_arr[] = array('term_name' => 'month_names_short_7', 'value' => 'Aug');
        $lang_arr[] = array('term_name' => 'month_names_short_8', 'value' => 'Sep');
        $lang_arr[] = array('term_name' => 'month_names_short_9', 'value' => 'Oct');
        $lang_arr[] = array('term_name' => 'month_names_short_10', 'value' => 'Nov');
        $lang_arr[] = array('term_name' => 'month_names_short_11', 'value' => 'Dec');
        $lang_arr[] = array('term_name' => 'urgency_0', 'value' => 'Inactive Items');
        $lang_arr[] = array('term_name' => 'urgency_1', 'value' => 'Green Items');
        $lang_arr[] = array('term_name' => 'urgency_2', 'value' => 'Yellow Items');
        $lang_arr[] = array('term_name' => 'urgency_3', 'value' => 'Red Items');
        $lang_arr[] = array('term_name' => 'urgency_4', 'value' => 'Complete Items');
        $lang_arr[] = array('term_name' => 'work_done_title', 'value' => 'Work Done');
        $lang_arr[] = array('term_name' => 'work_next_title', 'value' => 'Next Step');
        $lang_arr[] = array('term_name' => 'roadblock_title', 'value' => 'Roadblocks');
        $lang_arr[] = array('term_name' => 'no_estimate_given', 'value' => 'No Estimate Given');
        $lang_arr[] = array('term_name' => 'password_incorrect', 'value' => 'Incorrect Password or Email');
        $lang_arr[] = array('term_name' => 'files', 'value' => 'files');
        $lang_arr[] = array('term_name' => 'reply', 'value' => 'Reply');
        $lang_arr[] = array('term_name' => 'edit', 'value' => 'edit');
        $lang_arr[] = array('term_name' => 'proof_file', 'value' => 'Proof File');
        $lang_arr[] = array('term_name' => 'main_file', 'value' => 'Working File');
        $lang_arr[] = array('term_name' => 'uploading', 'value' => 'Uploading');
        $lang_arr[] = array('term_name' => 'user_admin', 'value' => 'Users');
        $lang_arr[] = array('term_name' => 'team_admin', 'value' => 'Teams');
        $lang_arr[] = array('term_name' => 'approval_admin', 'value' => 'Approval');
        $lang_arr[] = array('term_name' => 'object_admin', 'value' => 'Tasks and Projects');
        $lang_arr[] = array('term_name' => 'file_admin', 'value' => 'Files');
        $lang_arr[] = array('term_name' => 'account_admin', 'value' => 'Account');
        $lang_arr[] = array('term_name' => 'self_info', 'value' => 'My Info');
        $lang_arr[] = array('term_name' => 'self_spaces', 'value' => 'My Spaces');
        $lang_arr[] = array('term_name' => 'self_account', 'value' => 'My Account');
        $lang_arr[] = array('term_name' => 'first_name', 'value' => 'First Name');
        $lang_arr[] = array('term_name' => 'last_name', 'value' => 'Last Name');
        $lang_arr[] = array('term_name' => 'email', 'value' => 'e-mail');
        $lang_arr[] = array('term_name' => 'space_invite', 'value' => 'Please enter the e-mail of the invited user.');
        $lang_arr[] = array('term_name' => 'create_new_team', 'value' => 'Create a New Team');
        $lang_arr[] = array('term_name' => 'new_team', 'value' => 'New Team');
        $lang_arr[] = array('term_name' => 'invite_user', 'value' => 'Invite User');
        $lang_arr[] = array('term_name' => 'user_teams', 'value' => 'User Teams');
        $lang_arr[] = array('term_name' => 'team_users', 'value' => 'Team Users');
        $lang_arr[] = array('term_name' => 'edit_users', 'value' => 'edit users');
        $lang_arr[] = array('term_name' => 'edit_teams', 'value' => 'edit teams');
        $lang_arr[] = array('term_name' => 'edit_objects', 'value' => 'edit tasks and projects');
        $lang_arr[] = array('term_name' => 'edit_perm', 'value' => 'edit permissions');
        $lang_arr[] = array('term_name' => 'select_team_users', 'value' => 'Select the team users.');
        $lang_arr[] = array('term_name' => 'select_user_teams', 'value' => 'Select the user teams.');
        $lang_arr[] = array('term_name' => 'select_team_objects', 'value' => 'Select the team tasks and projects.');
        $lang_arr[] = array('term_name' => 'today_name', 'value' => 'Today');
        $lang_arr[] = array('term_name' => 'my_tasks_name', 'value' => 'My Tasks');
        $lang_arr[] = array('term_name' => 'team_tasks_name', 'value' => 'Team Tasks');
        $lang_arr[] = array('term_name' => 'file_name', 'value' => 'Files');
        $lang_arr[] = array('term_name' => 'depot_name', 'value' => 'All Tasks and Projects');
        $lang_arr[] = array('term_name' => 'reports_name', 'value' => 'Reports');
        $lang_arr[] = array('term_name' => 'add_status', 'value' => 'New Update');
        $lang_arr[] = array('term_name' => 'add_message', 'value' => 'New Comment');
        $lang_arr[] = array('term_name' => 'add_file', 'value' => 'New File');
        $lang_arr[] = array('term_name' => 'add_task', 'value' => 'New Task');
        $lang_arr[] = array('term_name' => 'move_object', 'value' => 'Move Tasks and Projects');
        $lang_arr[] = array('term_name' => 'logout', 'value' => 'Logout');
        $lang_arr[] = array('term_name' => 'settings', 'value' => 'Settings');
        $lang_arr[] = array('term_name' => 'help', 'value' => 'Help');
        $lang_arr[] = array('term_name' => 'new_space', 'value' => 'New Space');
        $lang_arr[] = array('term_name' => 'self_admin', 'value' => 'My Settings');
        $lang_arr[] = array('term_name' => 'cumWork', 'value' => 'Reported Work');
        $lang_arr[] = array('term_name' => 'cumBurnDown', 'value' => 'Burn-down Work-up');
        $lang_arr[] = array('term_name' => 'avatar_file_title', 'value' => 'Avatar File');
        $lang_arr[] = array('term_name' => 'avatar_file_instructions', 'value' => 'Please browse to select an image file (jpg, jpeg, png, gif).');
        $lang_arr[] = array('term_name' => 'user_obj_new_title', 'value' => 'My New Tasks');
        $lang_arr[] = array('term_name' => 'user_obj_urgent_title', 'value' => 'My Urgent Tasks');
        $lang_arr[] = array('term_name' => 'team_obj_urgent_title', 'value' => 'Urgent Team Tasks');
        $lang_arr[] = array('term_name' => 'new_avatar', 'value' => 'Update Avatar');
        $lang_arr[] = array('term_name' => 'cannot_post', 'value' => 'Sorry, can not post with missing information.');
        $lang_arr[] = array('term_name' => 'new_email', 'value' => 'Updated E-mail');
        $lang_arr[] = array('term_name' => 'del', 'value' => 'delete');
        $lang_arr[] = array('term_name' => 'del_warn', 'value' => 'You are about to delete this object and any sub objects inside it! Press Save to Confirm.');
        $lang_arr[] = array('term_name' => 'new_comment_title', 'value' => 'New Message Thread For=>  ');
        $lang_arr[] = array('term_name' => 'reply_comment_title', 'value' => 'Reply To:  ');
        $lang_arr[] = array('term_name' => 'update_task', 'value' => 'Work Update for:  ');
        $lang_arr[] = array('term_name' => 'new_file', 'value' => 'New File for:  ');
        $lang_arr[] = array('term_name' => 'update_file', 'value' => 'New Version for:  ');
        $lang_arr[] = array('term_name' => 'moving_objects', 'value' => 'Move Tasks and Projects');
        $lang_arr[] = array('term_name' => 'new_task', 'value' => 'New Sub Task in:  ');
        $lang_arr[] = array('term_name' => 'edit_objects', 'value' => 'Edit Task or Project');
        $lang_arr[] = array('term_name' => 'confirm_email_instructions', 'value' => 'Account Successfully Created - An email has been sent with a confirmation link. Please check your email for more details.');
        $lang_arr[] = array('term_name' => 'general_error_instructions', 'value' => 'An error occurred. Please try again later. If you continue to get this message, please check the support website, or contact support at sam@sampiplan.com');
        $lang_arr[] = array('term_name' => 'select_item_for_detail', 'value' => 'Select an item on the left to see more detail.');
        $lang_arr[] = array('term_name' => 'curr_user_reset_password', 'value' => 'Trouble remembering your password? No worries, just enter in your e-mail in the form and we will send you a link to confirm resetting it.');
        $lang_arr[] = array('term_name' => 'curr_user_welcome', 'value' => '<div>Welcome Back</div><div>Please enter your email and password in the form to log in.');
        $lang_arr[] = array('term_name' => 'new_user_welcome', 'value' => '<div>Hi there, welcome to Sampi Plan!</div><div>Please fill in the form and hit the Sign Up button.</div><div>If you already have an account, please press the Back to Login button and login using your existing email.</div>');
        $lang_arr[] = array('term_name' => 'duplicate_entry', 'value' => 'Sorry, this is duplicating something that already exists. Please check and try again.');
        $lang_arr[] = array('term_name' => 'ghost_status', 'value' => '(Pending)');
        $lang_arr[] = array('term_name' => 'invite_to_space_email_subject', 'value' => 'You have been invited to share a Sampi Plan workspace');
        $lang_arr[] = array('term_name' => 'invite_to_space_email_body', 'value' => 'You have been invited to a Sampi Plan workspace.<br><br>                 To accept please click this link, or copy and paste it into your browser:<br>                 http://app.sampiplan.com/index.html#invite_email/%s/invite/%s/space_id/%s<br><br>                 To find out more about Sampi Plan, go to http://www.sampiplan.com<br><br>                 If you do not want to join, just ignore this message.<br><br>                 Best Regards,<br><br>                 The Sampi Plan Team<br>                 sam@sampiplan.com');
        $lang_arr[] = array('term_name' => 'message_subject', 'value' => 'Subject');
        $lang_arr[] = array('term_name' => 'message_content', 'value' => 'Comment');
        $lang_arr[] = array('term_name' => 'message_reply', 'value' => 'Reply');
        $lang_arr[] = array('term_name' => 'work_done_today', 'value' => 'Work Done Today');
        $lang_arr[] = array('term_name' => 'work_remaining', 'value' => 'Work Remaining');
        $lang_arr[] = array('term_name' => 'what_did_you_do_today', 'value' => 'What did you do today?');
        $lang_arr[] = array('term_name' => 'what_are_next_steps', 'value' => 'What do you plan to do next?');
        $lang_arr[] = array('term_name' => 'current_issues', 'value' => 'Do you have any issues or roadblocks? (Leave blank if none.)');
        $lang_arr[] = array('term_name' => 'title', 'value' => 'Title');
        $lang_arr[] = array('term_name' => 'description', 'value' => 'Description');
        $lang_arr[] = array('term_name' => 'proof_file', 'value' => 'Proof File');
        $lang_arr[] = array('term_name' => 'doc_file', 'value' => 'Document File');
        $lang_arr[] = array('term_name' => 'submit_for_approval', 'value' => 'Submit for Review');
        $lang_arr[] = array('term_name' => 'move_source_object', 'value' => 'Select Projects and Tasks to Move:');
        $lang_arr[] = array('term_name' => 'select_target_object', 'value' => 'Select a Target Project or Task:');
        $lang_arr[] = array('term_name' => 'move_type', 'value' => 'Move Type');
        $lang_arr[] = array('term_name' => 'insert_before', 'value' => 'Insert Before');
        $lang_arr[] = array('term_name' => 'insert_after', 'value' => 'Insert After');
        $lang_arr[] = array('term_name' => 'insert_into', 'value' => 'Insert Into');
        $lang_arr[] = array('term_name' => 'name', 'value' => 'Name ');
        $lang_arr[] = array('term_name' => 'active_task', 'value' => 'Active Task');
        $lang_arr[] = array('term_name' => 'owner_name', 'value' => 'Owner');
        $lang_arr[] = array('term_name' => 'team_name', 'value' => 'Managing Team');
        $lang_arr[] = array('term_name' => 'start_date', 'value' => 'Start Date');
        $lang_arr[] = array('term_name' => 'time', 'value' => 'Time');
        $lang_arr[] = array('term_name' => 'finish_date', 'value' => 'Finish Date');
        $lang_arr[] = array('term_name' => 'service_level', 'value' => 'Service Level');
        $lang_arr[] = array('term_name' => 'none', 'value' => 'None');
        $lang_arr[] = array('term_name' => 'read_only', 'value' => 'Read Only');
        $lang_arr[] = array('term_name' => 'contribute', 'value' => 'Contribute');
        $lang_arr[] = array('term_name' => 'tasking', 'value' => 'Tasking');
        $lang_arr[] = array('term_name' => 'project_management', 'value' => 'Project Management');
        $lang_arr[] = array('term_name' => 'space_admin_level', 'value' => 'Space Admin Level');
        $lang_arr[] = array('term_name' => 'modify', 'value' => 'Modify');
        $lang_arr[] = array('term_name' => 'first', 'value' => 'First');
        $lang_arr[] = array('term_name' => 'last', 'value' => 'Last');
        $lang_arr[] = array('term_name' => 'reset_password', 'value' => 'Reset Password');
        $lang_arr[] = array('term_name' => 'back_to_login', 'value' => 'Back to Login');
        $lang_arr[] = array('term_name' => 'sign_up_new_account', 'value' => 'Sign Up for New Account');
        $lang_arr[] = array('term_name' => 'forgot_password', 'value' => 'Forgot Password');
        $lang_arr[] = array('term_name' => 'password', 'value' => 'Password');
        $lang_arr[] = array('term_name' => 'login', 'value' => 'Login');
        $lang_arr[] = array('term_name' => 'join_sampi_plan', 'value' => 'Join Sampi Plan');
        $lang_arr[] = array('term_name' => 'sign_up', 'value' => 'Sign Up');
        $lang_arr[] = array('term_name' => 'login_to_my_account', 'value' => 'Login to My Account');
        $lang_arr[] = array('term_name' => 'show_additional_week', 'value' => '+ One Week Back');
        $lang_arr[] = array('term_name' => 'comment_help_summary', 'value' => 'Share – Discuss a hot topic or keep notes.');
        $lang_arr[] = array('term_name' => 'comment_help_add', 'value' => 'Add a Conversation – Start a new discussion or note thread.');
        $lang_arr[] = array('term_name' => 'status_help_summary', 'value' => 'Status – See what work was done or report new work.');
        $lang_arr[] = array('term_name' => 'status_help_add', 'value' => 'Add a Status Update – Report new work, work to be done, or notes on the progress and next steps.');
        $lang_arr[] = array('term_name' => 'file_help_summary', 'value' => 'Files – Upload files up to 5GB. Download the latest version or look through previous ones.');
        $lang_arr[] = array('term_name' => 'file_help_add', 'value' => 'Add a New File – Upload a new file for sharing.');
        $lang_arr[] = array('term_name' => 'team_help_summary', 'value' => 'Team – See who is involved. The owners, managers, or anyone that has access to the Task or Project.');
        $lang_arr[] = array('term_name' => 'next', 'value' => 'Next');
        $lang_arr[] = array('term_name' => 'previous', 'value' => 'Back');
        $lang_arr[] = array('term_name' => 'cancel', 'value' => 'Cancel');
        $lang_arr[] = array('term_name' => 'save', 'value' => 'Save');
        $lang_arr[] = array('term_name' => 'summary_link', 'value' => 'Summary');
        $lang_arr[] = array('term_name' => 'tasks_projects_description_header', 'value' => 'Projects and Tasks');
        $lang_arr[] = array('term_name' => 'project_explanation', 'value' => 'Project: Shows a summary of all tasks and projects within. ');
        $lang_arr[] = array('term_name' => 'new_task_explanation', 'value' => 'New Task: This is a task that is not active. To make it active, update the status with an estimate of the work needed to finish the task.');
        $lang_arr[] = array('term_name' => 'on_time_task_explanation', 'value' => 'On Time Task: This task has some work remaining to be done, and there should be more than enough time to finish before the Finish Date.');
        $lang_arr[] = array('term_name' => 'low_risk_task_explanation', 'value' => 'Low Risk Task: This task and any related tasks have just enough time to finish before the Finish Date.');
        $lang_arr[] = array('term_name' => 'high_risk_task_explanation', 'value' => 'High Risk Task: This task and any related tasks require twice as much working time to complete than is left before the Finish Date.');
        $lang_arr[] = array('term_name' => 'complete_task_explanation', 'value' => 'Complete Task: This task has no work remaining to be done.');
        $lang_arr[] = array('term_name' => 'new_project', 'value' => 'New Sub Project in:  ');
        $lang_arr[] = array('term_name' => 'add_project', 'value' => 'New Project');
        $lang_arr[] = array('term_name' => 'start_driver', 'value' => 'Start By: ');
        $lang_arr[] = array('term_name' => 'finish_driver', 'value' => 'Finish By: ');

        return  ($lang_arr);
    }
}
?>
